import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ferias Desarrollo Social",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="bg-gray-800 p-4 text-white flex justify-between items-center">
            {/* Enlaces izquierda */}
            <div>
              <Link href="/" className="mr-4">
                Home
              </Link>
              <Link href="/feria" className="mr-4">
                Ferias
              </Link>
              <Link href="/about">About</Link>
            </div>

            {/* Botones derecha */}
            <div>
              <Link
                href="/auth/login"
                className="mr-4 border px-3 py-1 rounded hover:bg-gray-700"
              >
                Login
              </Link>

              <Link
                href="/auth/register"
                className="border px-3 py-1 rounded hover:bg-gray-700"
              >
                Register
              </Link>
            </div>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}
